/**
 * Tests for the deterministic manifest renderer.
 *
 * Covers rendering with all sections populated, empty sections with placeholders,
 * byte-identical deterministic output, pipe/newline escaping in descriptions,
 * regeneration command hint, and gray-matter frontmatter parseability.
 */

import { describe, it, expect } from 'vitest';
import matter from 'gray-matter';
import { renderManifest } from './manifest-renderer.js';
import type { CapabilityManifest } from './types.js';

/**
 * Helper: build a populated manifest for most tests.
 */
function buildPopulatedManifest(): CapabilityManifest {
  return {
    version: 1,
    generatedAt: '2026-01-15T12:00:00Z',
    contentHash: 'abc123def456gh78',
    skills: [
      {
        name: 'git-commit',
        description: 'Generates conventional commits',
        scope: 'project',
        contentHash: '1111111111111111',
      },
      {
        name: 'beautiful-commits',
        description: 'Enhanced commit messages',
        scope: 'user',
        contentHash: '2222222222222222',
      },
    ],
    agents: [
      {
        name: 'gsd-executor',
        description: 'Executes GSD plans autonomously',
        scope: 'project',
        tools: 'Read, Write, Bash',
        model: 'opus',
        contentHash: '3333333333333333',
      },
    ],
    teams: [
      {
        name: 'research-team',
        description: 'Research and analysis',
        scope: 'project',
        topology: 'leader-worker',
        memberCount: 3,
        contentHash: '4444444444444444',
      },
    ],
  };
}

describe('renderManifest', () => {
  // --------------------------------------------------------------------------
  // Test 1: renders manifest with all sections populated
  // --------------------------------------------------------------------------

  it('renders manifest with all sections populated', () => {
    const manifest = buildPopulatedManifest();
    const output = renderManifest(manifest);

    // YAML frontmatter block
    expect(output).toMatch(/^---\n/);
    expect(output).toContain('version: 1');
    expect(output).toContain('generatedAt');
    expect(output).toContain('contentHash');

    // Main heading
    expect(output).toContain('# Capabilities');

    // Auto-generated notice
    expect(output).toContain(
      '> Auto-generated by gsd-skill-creator. Do not edit manually.'
    );

    // Skills section with table
    expect(output).toContain('## Skills');
    expect(output).toContain('| Name | Scope | Description | Hash |');
    // 2 data rows in skills table
    expect(output).toContain('| git-commit |');
    expect(output).toContain('| beautiful-commits |');

    // Agents section with table
    expect(output).toContain('## Agents');
    expect(output).toContain(
      '| Name | Scope | Description | Tools | Model | Hash |'
    );
    // 1 data row in agents table
    expect(output).toContain('| gsd-executor |');

    // Teams section with table
    expect(output).toContain('## Teams');
    expect(output).toContain(
      '| Name | Scope | Description | Topology | Members | Hash |'
    );
    // 1 data row in teams table
    expect(output).toContain('| research-team |');
  });

  // --------------------------------------------------------------------------
  // Test 2: renders empty sections with placeholder text
  // --------------------------------------------------------------------------

  it('renders empty sections with placeholder text', () => {
    const manifest: CapabilityManifest = {
      version: 1,
      generatedAt: '2026-01-15T12:00:00Z',
      contentHash: 'emptymanifest00',
      skills: [],
      agents: [],
      teams: [],
    };

    const output = renderManifest(manifest);

    expect(output).toContain('No skills discovered.');
    expect(output).toContain('No agents discovered.');
    expect(output).toContain('No teams discovered.');

    // No table headers should appear in empty sections
    expect(output).not.toContain('| Name | Scope | Description | Hash |');
    expect(output).not.toContain(
      '| Name | Scope | Description | Tools | Model | Hash |'
    );
    expect(output).not.toContain(
      '| Name | Scope | Description | Topology | Members | Hash |'
    );
  });

  // --------------------------------------------------------------------------
  // Test 3: produces byte-identical output for same input
  // --------------------------------------------------------------------------

  it('produces byte-identical output for same input', () => {
    const manifest = buildPopulatedManifest();
    const output1 = renderManifest(manifest);
    const output2 = renderManifest(manifest);

    expect(output1).toBe(output2);
  });

  // --------------------------------------------------------------------------
  // Test 4: escapes pipe characters in descriptions
  // --------------------------------------------------------------------------

  it('escapes pipe characters in descriptions', () => {
    const manifest: CapabilityManifest = {
      version: 1,
      generatedAt: '2026-01-15T12:00:00Z',
      contentHash: 'pipetest0000000',
      skills: [
        {
          name: 'pipe-skill',
          description: 'Uses | pipe | in description',
          scope: 'project',
          contentHash: '5555555555555555',
        },
      ],
      agents: [],
      teams: [],
    };

    const output = renderManifest(manifest);

    // The pipe should be escaped as \| in the table row
    expect(output).toContain('Uses \\| pipe \\| in description');
    // The table structure should not be broken (skill row should be a single line)
    const lines = output.split('\n');
    const skillRow = lines.find(
      (l) => l.includes('pipe-skill') && l.startsWith('|')
    );
    expect(skillRow).toBeDefined();
    // Count pipe delimiters: should be 5 (4 columns + opening)
    const pipeCount = (skillRow!.match(/(?<!\\)\|/g) || []).length;
    expect(pipeCount).toBe(5);
  });

  // --------------------------------------------------------------------------
  // Test 5: escapes newlines in descriptions
  // --------------------------------------------------------------------------

  it('escapes newlines in descriptions', () => {
    const manifest: CapabilityManifest = {
      version: 1,
      generatedAt: '2026-01-15T12:00:00Z',
      contentHash: 'nltest000000000',
      skills: [
        {
          name: 'newline-skill',
          description: 'First line\nSecond line',
          scope: 'project',
          contentHash: '6666666666666666',
        },
      ],
      agents: [],
      teams: [],
    };

    const output = renderManifest(manifest);

    // Find the table row for the skill
    const lines = output.split('\n');
    const skillRow = lines.find(
      (l) => l.includes('newline-skill') && l.startsWith('|')
    );
    expect(skillRow).toBeDefined();

    // The row should contain "First line Second line" (newline replaced with space)
    expect(skillRow).toContain('First line Second line');
  });

  // --------------------------------------------------------------------------
  // Test 6: renders regeneration command hint
  // --------------------------------------------------------------------------

  it('renders regeneration command hint', () => {
    const manifest = buildPopulatedManifest();
    const output = renderManifest(manifest);

    expect(output).toContain(
      '> Regenerate: `skill-creator capabilities generate`'
    );
  });

  // --------------------------------------------------------------------------
  // Test 7: frontmatter is parseable by gray-matter
  // --------------------------------------------------------------------------

  it('frontmatter is parseable by gray-matter', () => {
    const manifest = buildPopulatedManifest();
    const output = renderManifest(manifest);

    const parsed = matter(output);

    expect(parsed.data.version).toBe(1);
    expect(parsed.data.contentHash).toBe('abc123def456gh78');
    expect(typeof parsed.data.generatedAt).toBe('string');
  });
});
