// Types for automated test generation
//
// These types support the test corpus generation system that creates
// positive and negative test cases from skill descriptions.

/**
 * A generated test case before it's saved to the TestStore.
 *
 * Unlike TestCase, this doesn't have an ID or createdAt timestamp -
 * those are added when the test is approved and persisted.
 */
export interface GeneratedTest {
  /**
   * The test prompt text - a realistic user message.
   */
  prompt: string;

  /**
   * Expected activation behavior.
   *
   * - `positive`: Skill SHOULD activate for this prompt
   * - `negative`: Skill should NOT activate for this prompt
   *
   * Note: No 'edge-case' for generated tests - those are harder
   * to auto-generate well and should be added manually.
   */
  expected: 'positive' | 'negative';

  /**
   * How the test was generated.
   *
   * - `llm`: Generated by Claude Haiku from skill description
   * - `heuristic`: Generated by NLP phrase extraction (fallback)
   * - `cross-skill`: Derived from a competing skill's domain
   */
  source: 'llm' | 'heuristic' | 'cross-skill';

  /**
   * Optional description of what this test validates.
   */
  description?: string;

  /**
   * For negative tests: why the skill should NOT activate.
   * Examples: "belongs to auth-skill", "out of domain"
   */
  reason?: string;

  /**
   * For cross-skill negatives: which skill this prompt came from.
   * Helps understand why this is a negative test.
   */
  competitorSkill?: string;
}

/**
 * Information about a skill for test generation.
 *
 * Contains the essential fields needed to generate test cases.
 */
export interface SkillInfo {
  /**
   * The skill's name (used for identification).
   */
  name: string;

  /**
   * The skill's description text.
   * Primary source for generating positive tests.
   */
  description: string;

  /**
   * Optional "when to use" guidance from skill body or metadata.
   * Provides additional context for test generation.
   */
  whenToUse?: string;
}

/**
 * Strategy interface for test generators.
 *
 * Allows different implementations (LLM, heuristic, cross-skill)
 * to be used interchangeably.
 */
export interface GeneratorStrategy {
  /**
   * Generate positive test cases for a skill.
   *
   * @param skill - Skill information for generation
   * @param count - Number of tests to generate
   * @returns Array of generated positive tests (may be fewer than count)
   */
  generatePositive(skill: SkillInfo, count: number): Promise<GeneratedTest[]>;

  /**
   * Generate negative test cases for a skill.
   *
   * @param skill - Skill information for generation
   * @param count - Number of tests to generate
   * @returns Array of generated negative tests (may be fewer than count)
   */
  generateNegative(skill: SkillInfo, count: number): Promise<GeneratedTest[]>;
}

/**
 * Options for the test generation process.
 */
export interface GenerateOptions {
  /**
   * Number of positive tests to generate.
   */
  positiveCount: number;

  /**
   * Number of negative tests to generate.
   */
  negativeCount: number;
}
