/**
 * Event type system for inter-skill communication.
 *
 * Defines Zod schemas for:
 * - EventNameSchema: enforces category:action naming format
 * - SkillEventsSchema: declares what events a skill emits and listens for
 * - EventEntrySchema: full event entry for JSONL storage
 *
 * All schemas use .passthrough() for forward compatibility.
 */

import { z } from 'zod';

// ============================================================================
// EventNameSchema
// ============================================================================

/**
 * Validates event names in category:action format.
 * Examples: 'lint:complete', 'test:fail', 'deploy-prod:rollback'
 *
 * Pattern: lowercase letters/digits/hyphens, colon separator, same for action.
 * Must start with a letter on each side of the colon.
 */
export const EventNameSchema = z.string().regex(
  /^[a-z][a-z0-9-]*:[a-z][a-z0-9-]*$/,
  'Event name must be in category:action format (e.g., lint:complete)',
);

// ============================================================================
// SkillEventsSchema
// ============================================================================

/**
 * Schema for skill event declarations in extension frontmatter.
 *
 * Skills declare which events they emit and listen for.
 * Both fields are optional (a skill may only emit or only listen).
 */
export const SkillEventsSchema = z.object({
  emits: z.array(EventNameSchema).optional(),
  listens: z.array(EventNameSchema).optional(),
}).passthrough();

export type SkillEvents = z.infer<typeof SkillEventsSchema>;

// ============================================================================
// EventEntrySchema
// ============================================================================

/**
 * Schema for a single event entry in the JSONL event store.
 *
 * Events are stored in pattern envelope format ({timestamp, category: 'events', data}).
 * This schema validates the inner data payload.
 *
 * Lifecycle: pending -> consumed (by explicit consume() call) or expired (TTL exceeded).
 */
export const EventEntrySchema = z.object({
  event_name: EventNameSchema,
  emitted_by: z.string().min(1),
  status: z.enum(['pending', 'consumed', 'expired']),
  emitted_at: z.string(),
  consumed_by: z.string().nullable().default(null),
  consumed_at: z.string().nullable().default(null),
  ttl_hours: z.number().default(24),
}).passthrough();

export type EventEntry = z.infer<typeof EventEntrySchema>;

// ============================================================================
// EventConnectionSuggestion
// ============================================================================

/**
 * Suggested event connection between two skills based on co-activation patterns.
 *
 * Generated by analyzing session observation data to find skills that
 * frequently activate together and could benefit from event-driven coordination.
 */
export interface EventConnectionSuggestion {
  emitterSkill: string;
  listenerSkill: string;
  suggestedEvent: string;
  coActivationScore: number;
  sessionCount: number;
}
